import React, { useEffect, useMemo, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import BackButton from "../components/auth/BackButton";
import PrimaryButton from "../components/buttons/PrimaryButton";
import Colors from "../constants/colors";
import { useJournal } from "../features/journal/JournalContext";
import { JournalEntry } from "../features/journal/journalRepository";
import { MoodId, moodConfigurations } from "../features/mood/moodRepository";

function isMoodId(value: string | undefined): value is MoodId { return Boolean(value && value in moodConfigurations); }

export default function JournalEditorScreen() {
  const router = useRouter(); const { id, mood } = useLocalSearchParams<{ id?: string; mood?: string }>(); const { getEntryById, createEntry, updateEntry } = useJournal(); const [existing, setExisting] = useState<JournalEntry | null>(null); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const validMood = isMoodId(mood) ? mood : null; const displayMood = existing?.mood ?? validMood; const original = useMemo(() => ({ title: existing?.title ?? "", content: existing?.content ?? "" }), [existing]);
  useEffect(() => { let active = true; if (!id) return; setLoading(true); getEntryById(id).then((entry) => { if (active && entry) { setExisting(entry); setTitle(entry.title); setContent(entry.content); } if (active && !entry) Alert.alert("Entry not found", "This journal entry may have been deleted."); }).catch(() => active && Alert.alert("Unable to load entry", "Please return to your journal and try again.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [getEntryById, id]);
  const leave = () => { if (!saving && (title !== original.title || content !== original.content)) Alert.alert("Discard changes?", "Your unsaved changes will be lost.", [{ text: "Keep writing", style: "cancel" }, { text: "Discard", style: "destructive", onPress: () => router.back() }]); else router.back(); };
  const save = async () => { if (saving) return; if (!title.trim() || !content.trim()) { Alert.alert("Complete your entry", "Add a title and your journal entry before saving."); return; } setSaving(true); try { if (existing) { const updated = await updateEntry(existing.id, { title, content }); if (!updated) throw new Error("This entry is no longer available."); router.replace(`/journal-detail?id=${existing.id}`); } else { const entry = await createEntry({ title, content, source: displayMood ? "mood" : "journal", mood: displayMood, moodLabel: displayMood ? moodConfigurations[displayMood].label : null, moodEmoji: displayMood ? moodConfigurations[displayMood].emoji : null, moodSubtitle: displayMood ? `You logged ${moodConfigurations[displayMood].label}` : null }); router.replace(`/journal-detail?id=${entry.id}`); } } catch (error) { Alert.alert("Could not save entry", error instanceof Error ? error.message : "Please try again."); } finally { setSaving(false); } };
  const canSave = Boolean(title.trim() && content.trim()) && !saving && !loading;
  return <SafeAreaView style={styles.screen} edges={["top", "bottom"]}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.top}><BackButton onPress={leave} /><Text style={styles.header}>{existing ? "Edit Entry" : "New Entry"}</Text><Text onPress={canSave ? save : undefined} style={[styles.save, !canSave ? styles.saveDisabled : null]}>{saving ? "Saving…" : "Save"}</Text></View><View style={styles.meta}><Text style={styles.date}>{new Date(existing?.createdAt ?? Date.now()).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</Text><Text style={styles.private}>♧ Private</Text></View>{displayMood ? <View style={styles.moodBanner}><Text style={styles.moodEmoji}>{moodConfigurations[displayMood].emoji}</Text><Text style={styles.moodText}>{existing?.moodSubtitle ?? `You logged ${moodConfigurations[displayMood].label}`}</Text></View> : null}{loading ? <Text style={styles.loading}>Loading entry…</Text> : <><TextInput value={title} onChangeText={setTitle} placeholder="Entry title..." placeholderTextColor="#9C8AA8" style={styles.titleInput} /><TextInput value={content} onChangeText={setContent} placeholder="Write what's on your mind..." placeholderTextColor="#9C8AA8" multiline textAlignVertical="top" style={styles.contentInput} /><PrimaryButton title="Save Entry" onPress={save} disabled={!canSave} loading={saving} style={styles.button} /></>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, flex: { flex: 1 }, content: { flexGrow: 1, paddingHorizontal: 17, paddingTop: 45, paddingBottom: 35 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, header: { color: Colors.darkPurple, fontSize: 19, fontWeight: "700" }, save: { color: "#B46BE1", fontSize: 16, fontWeight: "700" }, saveDisabled: { color: "#D8C3E8" }, meta: { flexDirection: "row", justifyContent: "space-between", marginTop: 34 }, date: { color: "#A277C5", fontSize: 16 }, private: { color: "#C19ADB", fontSize: 16 }, moodBanner: { flexDirection: "row", alignItems: "center", gap: 9, marginTop: 18, padding: 13, borderRadius: 16, backgroundColor: "#F0E2FF" }, moodEmoji: { fontSize: 21 }, moodText: { color: "#805A98", fontSize: 16, fontWeight: "600" }, loading: { marginTop: 40, color: "#A277C5", textAlign: "center" }, titleInput: { marginTop: 27, color: Colors.darkPurple, fontSize: 27, fontWeight: "700" }, contentInput: { minHeight: 265, marginTop: 24, color: Colors.darkPurple, fontSize: 18, lineHeight: 28 }, button: { marginTop: 22 } });
