import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import BottomNavigation from "../components/navigation/BottomNavigation";
import Colors from "../constants/colors";
import { useJournal } from "../features/journal/JournalContext";
import { formatEntryDateTime } from "../features/journal/journalRepository";

export default function JournalScreen() {
  const router = useRouter(); const { entries, loading, error, searchEntries } = useJournal(); const [query, setQuery] = useState("");
  useEffect(() => { const timeout = setTimeout(() => { void searchEntries(query); }, 300); return () => clearTimeout(timeout); }, [query, searchEntries]);
  return <SafeAreaView style={styles.screen} edges={["top"]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.title}>My Journal</Text><View style={styles.privateRow}><Ionicons name="lock-closed-outline" size={15} color="#C19ADB" /><Text style={styles.privateText}>Stored privately on this device</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel="Create journal entry" onPress={() => router.push("/journal-editor")} style={styles.add}><Ionicons name="add" size={31} color={Colors.white} /></Pressable></View><View style={styles.search}><Ionicons name="search-outline" size={21} color="#B096C4" /><TextInput value={query} onChangeText={setQuery} placeholder="Search entries..." placeholderTextColor="#9D8AA8" style={styles.searchInput} /></View>{loading ? <View style={styles.feedback}><ActivityIndicator color="#A767CC" /><Text style={styles.feedbackText}>Loading your private journal…</Text></View> : error ? <View style={styles.feedback}><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void searchEntries(query)}><Text style={styles.retry}>Try again</Text></Pressable></View> : entries.length ? <View style={styles.entries}>{entries.map((entry) => <Pressable key={entry.id} accessibilityRole="button" onPress={() => router.push(`/journal-detail?id=${entry.id}`)} style={styles.entryCard}><View style={styles.entryTop}><Text style={styles.entryTitle}>{entry.title}</Text>{entry.moodEmoji ? <Text style={styles.entryMood}>{entry.moodEmoji}</Text> : null}</View><Text numberOfLines={2} style={styles.preview}>{entry.content}</Text><Text style={styles.date}>{formatEntryDateTime(entry.createdAt)}</Text></Pressable>)}</View> : <EmptyState query={query} onCreate={() => router.push("/journal-editor")} />}</ScrollView><BottomNavigation activeTab="Journal" /></SafeAreaView>;
}

function EmptyState({ query, onCreate }: { query: string; onCreate: () => void }) { const searching = Boolean(query.trim()); return <View style={styles.empty}><Text style={styles.emptyIcon}>{"\u{1F4D4}"}</Text><Text style={styles.emptyTitle}>{searching ? "No matching entries" : "Your journal is empty"}</Text><Text style={styles.emptySubtitle}>{searching ? "Try a different word or phrase." : "Start writing your thoughts and memories."}</Text>{!searching ? <Pressable accessibilityRole="button" onPress={onCreate} style={styles.emptyButton}><Text style={styles.emptyButtonText}>Create Entry</Text></Pressable> : null}</View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, content: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 40, paddingBottom: 29, gap: 17 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { color: Colors.darkPurple, fontSize: 28, fontWeight: "700" }, privateRow: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 11 }, privateText: { color: "#C19ADB", fontSize: 15 }, add: { width: 46, height: 46, alignItems: "center", justifyContent: "center", borderRadius: 23, backgroundColor: "#CE82F5" }, search: { height: 52, paddingHorizontal: 19, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: "#E7D5F7", borderRadius: 19, backgroundColor: Colors.white }, searchInput: { flex: 1, color: Colors.darkPurple, fontSize: 17 }, entries: { gap: 16 }, entryCard: { padding: 20, borderWidth: 1, borderColor: "#E8D9F5", borderRadius: 29, backgroundColor: Colors.white }, entryTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, entryTitle: { flex: 1, color: Colors.darkPurple, fontSize: 21, fontWeight: "700" }, entryMood: { marginLeft: 12, fontSize: 22 }, preview: { marginTop: 13, color: "#765D87", fontSize: 18, lineHeight: 28 }, date: { marginTop: 12, color: "#C29FDB", fontSize: 15 }, feedback: { alignItems: "center", paddingVertical: 45, gap: 12 }, feedbackText: { color: "#A277C5", fontSize: 16 }, errorText: { color: "#D05063", fontSize: 16, textAlign: "center" }, retry: { color: "#A767CC", fontSize: 16, fontWeight: "700" }, empty: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 100 }, emptyIcon: { fontSize: 54 }, emptyTitle: { marginTop: 15, color: Colors.darkPurple, fontSize: 22, fontWeight: "700" }, emptySubtitle: { marginTop: 8, color: "#A277C5", fontSize: 16, textAlign: "center" }, emptyButton: { marginTop: 25, paddingHorizontal: 28, paddingVertical: 15, borderRadius: 20, backgroundColor: "#D889F7" }, emptyButtonText: { color: Colors.darkPurple, fontSize: 17, fontWeight: "700" } });
