import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import BackButton from "../components/auth/BackButton";
import BottomNavigation from "../components/navigation/BottomNavigation";
import DeleteEntryDialog from "../components/journal/DeleteEntryDialog";
import Colors from "../constants/colors";
import { useJournal } from "../features/journal/JournalContext";
import { formatEntryDateTime, JournalEntry } from "../features/journal/journalRepository";

export default function JournalDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const { getEntryById, deleteEntry } = useJournal(); const [entry, setEntry] = useState<JournalEntry | null>(null); const [loading, setLoading] = useState(true); const [showDelete, setShowDelete] = useState(false); const [deleting, setDeleting] = useState(false);
  useEffect(() => { let active = true; if (!id) { setLoading(false); return; } getEntryById(id).then((result) => active && setEntry(result)).catch(() => active && Alert.alert("Unable to load entry", "Please return to your journal and try again.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [getEntryById, id]);
  const remove = async () => { if (!entry || deleting) return; setDeleting(true); try { const deleted = await deleteEntry(entry.id); if (!deleted) throw new Error("Entry is unavailable."); setShowDelete(false); router.replace("/journal"); } catch (error) { Alert.alert("Could not delete entry", error instanceof Error ? error.message : "Please try again."); } finally { setDeleting(false); } };
  if (loading) return <SafeAreaView style={styles.screen}><View style={styles.missing}><ActivityIndicator color="#A767CC" /><Text style={styles.back}>Loading entry…</Text></View></SafeAreaView>;
  if (!entry) return <SafeAreaView style={styles.screen}><View style={styles.missing}><Text style={styles.title}>Entry not found</Text><Text onPress={() => router.replace("/journal")} style={styles.back}>Back to Journal</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.screen} edges={["top"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><BackButton onPress={() => router.back()} /><View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => router.push(`/journal-editor?id=${entry.id}`)}><Ionicons name="pencil-outline" size={27} color="#A767CC" /></Pressable><Pressable accessibilityRole="button" onPress={() => setShowDelete(true)}><Ionicons name="trash-outline" size={26} color="#FB626B" /></Pressable></View></View><View style={styles.meta}>{entry.moodEmoji ? <View style={styles.moodSquare}><Text style={styles.moodEmoji}>{entry.moodEmoji}</Text></View> : null}<View style={styles.metaText}><Text style={styles.date}>{formatEntryDateTime(entry.createdAt)}</Text>{entry.moodLabel ? <Text style={styles.moodLabel}>{entry.moodLabel}</Text> : null}</View><Text style={styles.private}>♧ Private</Text></View><Text style={styles.title}>{entry.title}</Text><Text selectable style={styles.body}>{entry.content}</Text></ScrollView><BottomNavigation activeTab="Journal" /><DeleteEntryDialog visible={showDelete} onCancel={() => setShowDelete(false)} onDelete={() => void remove()} /></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, content: { flexGrow: 1, paddingHorizontal: 19, paddingTop: 45, paddingBottom: 28 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, actions: { flexDirection: "row", gap: 20, alignItems: "center" }, meta: { flexDirection: "row", alignItems: "center", marginTop: 35 }, moodSquare: { width: 60, height: 60, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: "#FFF6D9" }, moodEmoji: { fontSize: 29 }, metaText: { marginLeft: 14, flex: 1 }, date: { color: "#A277C5", fontSize: 16 }, moodLabel: { marginTop: 5, color: "#E0A000", fontSize: 16, fontWeight: "600" }, private: { color: "#C19ADB", fontSize: 16 }, title: { marginTop: 34, color: Colors.darkPurple, fontSize: 31, fontWeight: "700" }, body: { marginTop: 19, color: Colors.darkPurple, fontSize: 19, lineHeight: 30 }, missing: { flex: 1, alignItems: "center", justifyContent: "center" }, back: { marginTop: 14, color: "#A767CC", fontSize: 17 } });
