import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";

import BottomNavigation from "../components/navigation/BottomNavigation";
import PrimaryButton from "../components/buttons/PrimaryButton";
import Colors from "../constants/colors";
import { MoodId, moodConfigurations, monthlyMoodHistory, weeklyMoodHistory } from "../features/mood/moodRepository";
import { useMoodHistory } from "../features/mood/MoodHistoryContext";

type Tab = "Today" | "Weekly" | "Monthly";
const moodList = Object.values(moodConfigurations);

export default function MoodScreen() {
  const router = useRouter();
  const { loggedMood } = useMoodHistory();
  const [tab, setTab] = useState<Tab>("Today");
  const [selectedMood, setSelectedMood] = useState<MoodId>("angry");
  return <SafeAreaView style={styles.screen} edges={["top"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>Mood</Text><View style={styles.tabs}>{(["Today", "Weekly", "Monthly"] as Tab[]).map((item) => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: tab === item }} onPress={() => setTab(item)} style={[styles.tab, tab === item ? styles.activeTab : null]}><Text style={[styles.tabText, tab === item ? styles.activeTabText : null]}>{item}</Text></Pressable>)}</View>{tab === "Today" ? <TodayView selectedMood={selectedMood} onSelect={setSelectedMood} onSave={() => router.push(`/mood-result?mood=${selectedMood}`)} /> : null}{tab === "Weekly" ? <WeeklyView loggedMood={loggedMood} /> : null}{tab === "Monthly" ? <MonthlyView loggedMood={loggedMood} /> : null}</ScrollView><BottomNavigation activeTab="Mood" /></SafeAreaView>;
}

function TodayView({ selectedMood, onSelect, onSave }: { selectedMood: MoodId; onSelect: (id: MoodId) => void; onSave: () => void }) { return <View style={styles.today}><View><Text style={styles.question}>How are you feeling today?</Text><Text style={styles.subtitle}>Choose the mood that feels closest to how you feel right now.</Text></View><View style={styles.moodGrid}>{moodList.map((mood) => <Pressable key={mood.id} accessibilityRole="radio" accessibilityState={{ selected: selectedMood === mood.id }} onPress={() => onSelect(mood.id)} style={[styles.moodCard, { backgroundColor: mood.color }, selectedMood === mood.id ? styles.selectedMood : null]}><Text style={styles.moodEmoji}>{mood.emoji}</Text><Text style={styles.moodName}>{mood.label}</Text>{selectedMood === mood.id ? <View style={styles.check}><Text style={styles.checkText}>✓</Text></View> : null}</Pressable>)}</View><PrimaryButton title="Save Mood" onPress={onSave} style={styles.saveButton} /></View>; }
function WeeklyView({ loggedMood }: { loggedMood: MoodId | null }) { const history = [...weeklyMoodHistory]; if (loggedMood) history[history.length - 1] = loggedMood; const counts = history.reduce<Record<string, number>>((result, mood) => { if (mood) result[mood] = (result[mood] ?? 0) + 1; return result; }, {}); const frequent = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] as MoodId; return <View style={styles.report}><Text style={styles.question}>Your week in moods</Text><View style={styles.weekRow}>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <View key={day} style={styles.day}><Text style={styles.dayName}>{day}</Text><Text style={styles.historyEmoji}>{history[index] ? moodConfigurations[history[index] as MoodId].emoji : ""}</Text></View>)}</View><View style={styles.insightCard}><Text style={styles.insightTitle}>Weekly insight</Text><Text style={styles.insightText}>You checked in {history.filter(Boolean).length} times. {frequent ? `${moodConfigurations[frequent].label} appeared most often this week.` : "Every check-in matters."}</Text></View></View>; }
function MonthlyView({ loggedMood }: { loggedMood: MoodId | null }) { const now = new Date(); const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).getDay(); const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: firstDay + days }, (_, index) => index < firstDay ? null : index - firstDay + 1); const moods = { ...monthlyMoodHistory, ...(loggedMood ? { [now.getDate()]: loggedMood } : {}) }; return <View style={styles.report}><Text style={styles.question}>{now.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</Text><View style={styles.calendar}>{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <Text key={day} style={styles.calendarWeekday}>{day}</Text>)}{cells.map((date, index) => <View key={`${date}-${index}`} style={styles.calendarDay}>{date ? <><Text style={styles.date}>{date}</Text><Text style={styles.calendarEmoji}>{moods[date] ? moodConfigurations[moods[date]].emoji : ""}</Text></> : null}</View>)}</View></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, content: { flexGrow: 1, paddingHorizontal: 12, paddingTop: 38, paddingBottom: 28, gap: 18 }, title: { color: Colors.darkPurple, fontSize: 29, fontWeight: "700" }, tabs: { flexDirection: "row", gap: 9 }, tab: { paddingHorizontal: 21, paddingVertical: 10, borderWidth: 1, borderColor: "#E8D9F5", borderRadius: 22, backgroundColor: Colors.white }, activeTab: { borderColor: "#D98CF6", backgroundColor: "#DE91F7" }, tabText: { color: "#A277C5", fontSize: 16 }, activeTabText: { color: Colors.darkPurple, fontWeight: "600" }, today: { gap: 19 }, question: { color: "#4D2C70", fontSize: 19, fontWeight: "600" }, subtitle: { marginTop: 4, color: "#A277C5", fontSize: 16, lineHeight: 23 }, moodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 }, moodCard: { position: "relative", width: "48.2%", height: 90, flexDirection: "row", alignItems: "center", gap: 16, paddingHorizontal: 23, borderRadius: 29 }, selectedMood: { borderWidth: 2.5, borderColor: "#FF6C72" }, moodEmoji: { fontSize: 32 }, moodName: { color: Colors.darkPurple, fontSize: 18, fontWeight: "600" }, check: { position: "absolute", top: 14, right: 14, width: 25, height: 25, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#F66C73" }, checkText: { color: Colors.white, fontWeight: "700" }, saveButton: { marginTop: 10 }, report: { gap: 23 }, weekRow: { flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 23, backgroundColor: Colors.white }, day: { alignItems: "center", gap: 10 }, dayName: { color: "#A27BB9", fontSize: 11 }, historyEmoji: { fontSize: 23 }, insightCard: { padding: 22, borderRadius: 24, backgroundColor: "#F0E2FF" }, insightTitle: { color: Colors.darkPurple, fontSize: 18, fontWeight: "700" }, insightText: { marginTop: 8, color: "#805A98", fontSize: 15, lineHeight: 23 }, calendar: { flexDirection: "row", flexWrap: "wrap", padding: 13, borderRadius: 23, backgroundColor: Colors.white }, calendarWeekday: { width: "14.285%", color: "#A27BB9", fontSize: 11, textAlign: "center" }, calendarDay: { width: "14.285%", height: 53, alignItems: "center", paddingTop: 8 }, date: { color: Colors.darkPurple, fontSize: 13 }, calendarEmoji: { marginTop: 3, fontSize: 17 }, });
